### ISSUE TITLE
Package org.whipper.xml missing some classes

### ISSUE THREAD

**Issue by refadai** [teiid/whipper#8]
Hello,
I'm new to GitHub. I think that a lot of classes are missing in package org.whipper.xml. For example QueryResultType which is referred in class ExpectedResultHolder. Also class MetaQuerySetResultMode refers to missing classes. At the present time, it seems there is only one class in org.whipper.xml package, while we should have more than 10.

Regards
Renaud

**Comment by jdurani** [comment]
Hello,
those classes are generated automatically from XSD schema. Clone the repository and run `mvn generate-sources` and maven will generate them for you.
